/* Users */
export const SET_USER_INFO = "SET_USER_INFO";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

/* Contacts */
export const REQUEST_CONTACTS = "REQUEST_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const REQUEST_CONTACT_DETAILS = "REQUEST_CONTACT_DETAILS";
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS";
export const GET_CONTACT_DETAILS_FAIL = "GET_CONTACT_DETAILS_FAIL";

export const REQUEST_CONTACT_DELETE = "REQUEST_CONTACT_DELETE";
export const CONTACT_DELETE_SUCCESS = "CONTACT_DELETE_SUCCESS";
export const CONTACT_DELETE_FAIL = "CONTACT_DELETE_FAIL";

export const REQUEST_CREATE_CONTACT = "REQUEST_CREATE_CONTACT";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";

export const REQUEST_UPDATE_CONTACT = "REQUEST_UPDATE_CONTACT";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";

export const UPLOAD_PICTURE_REQUEST = "UPLOAD_PICTURE_REQUEST";
export const TAKE_PICTURE = "TAKE_PICTURE";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const GET_IMAGE_URL = "GET_IMAGE_URL";

export const UPLOAD_PICTURE_SUCCESS = "UPLOAD_PICTURE_SUCCESS";
export const UPLOAD_PICTURE_FAIL = "UPLOAD_PICTURE_FAIL";

/**
 * Games
 */
export const GAME_LIST_REQUEST = "GAME_LIST_REQUEST";
export const GAME_LIST_SUCCESS = "GAME_LIST_SUCCESS";
export const GAME_LIST_FAIL = "GAME_LIST_FAIL";
